title = "Cookbook"
baseURL = "https://eweix.github.io"
enableGitInfo = 'true'
useResourceCacheWhen = 'always'

# author info
[params.author]
  name = 'Elliott Weix'
  email = 'elliott@weix.us'
  short = 'eweix'

[[Menus.main]]
  Name = "Tags"
  URL = "/tags"
[[Menus.main]]
  Name = "Favorites"
  URL = "/favorites"

[permalinks]
  recipes = "/:slug"
