title = "Cookbook"
baseURL = "https://eweix.github.io/"
enableGitInfo = 'true'
useResourceCacheWhen = 'always'

# author info
[params.author]
  name = 'Elliott Weix'
  email = 'elliott@weix.us'
  short = 'eweix'

[[Menus.main]]
  Name = "Tags"
  URL = "/tags"
  weight = 20
[[Menus.main]]
  Name = "Favorites"
  URL = "/favorites"
  weight = 10
[[Menus.main]]
  Name = "About"
  URL = "/about"
  weight = 30

[permalinks]
  recipes = ":slug"
